name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Linting
      run: swift run swiftlint
    - name: Build
      run: swift build -v
    - name: Run tests
      env:
          TEST_APP_ID: ${{ secrets.CI_APP_ID }}
          TEST_APP_KEY: ${{ secrets.CI_APP_KEY }}
          TEST_APP_SECRET: ${{ secrets.CI_APP_SECRET }}
          TEST_APP_CLUSTER: ${{ secrets.CI_APP_CLUSTER }}
          TEST_ENCRYPTION_MASTER_KEY: ${{ secrets.CI_ENCRYPTION_MASTER_KEY }}
      run: swift test -v
